/*
 * Decompiled with CFR 0.152.
 * 
 * Could not load the following classes:
 *  net.minecraft.util.ResourceLocation
 *  net.minecraftforge.fml.client.registry.RenderingRegistry
 *  net.minecraftforge.fml.common.ModMetadata
 *  net.minecraftforge.fml.common.event.FMLInitializationEvent
 *  net.minecraftforge.fml.common.event.FMLPostInitializationEvent
 *  net.minecraftforge.fml.common.event.FMLPreInitializationEvent
 *  net.minecraftforge.fml.common.event.FMLServerStartingEvent
 *  net.minecraftforge.fml.common.registry.EntityRegistry
 */
package com.rejahtavi.rfp2;

import com.rejahtavi.rfp2.EntityPlayerDummy;
import com.rejahtavi.rfp2.IProxy;
import com.rejahtavi.rfp2.RFP2;
import com.rejahtavi.rfp2.RFP2Config;
import com.rejahtavi.rfp2.RFP2State;
import com.rejahtavi.rfp2.RenderPlayerDummy;
import net.minecraft.util.ResourceLocation;
import net.minecraftforge.fml.client.registry.RenderingRegistry;
import net.minecraftforge.fml.common.ModMetadata;
import net.minecraftforge.fml.common.event.FMLInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPostInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;
import net.minecraftforge.fml.common.event.FMLServerStartingEvent;
import net.minecraftforge.fml.common.registry.EntityRegistry;

public class ClientProxy
implements IProxy {
    @Override
    public void preInit(FMLPreInitializationEvent event) {
        RFP2.logger = event.getModLog();
        ModMetadata m2 = event.getModMetadata();
        m2.modId = "rfp2";
        m2.name = "Real First Person 2";
        m2.version = "1.12.2-1.3.2";
        m2.description = "Implements full body rendering in first person.";
        m2.authorList.clear();
        m2.authorList.add("Rejah Tavi");
        m2.authorList.add("don_bruce");
        m2.autogenerated = false;
        RenderingRegistry.registerEntityRenderingHandler(EntityPlayerDummy.class, RenderPlayerDummy::new);
    }

    @Override
    public void init(FMLInitializationEvent event) {
        RFP2.config = new RFP2Config();
        EntityRegistry.registerModEntity((ResourceLocation)new ResourceLocation("rfp2", "PlayerDummy"), EntityPlayerDummy.class, (String)"PlayerDummy", (int)0, (Object)"rfp2", (int)5, (int)100, (boolean)false);
    }

    @Override
    public void postInit(FMLPostInitializationEvent event) {
        RFP2.state = new RFP2State();
    }

    @Override
    public void serverStarting(FMLServerStartingEvent event) {
    }
}

