/*
 * Decompiled with CFR 0.152.
 * 
 * Could not load the following classes:
 *  net.minecraft.command.ICommand
 *  net.minecraft.command.ServerCommandManager
 *  net.minecraft.nbt.NBTTagCompound
 *  net.minecraft.server.MinecraftServer
 *  net.minecraftforge.common.config.Configuration
 *  net.minecraftforge.fml.common.Mod
 *  net.minecraftforge.fml.common.Mod$EventHandler
 *  net.minecraftforge.fml.common.Mod$Instance
 *  net.minecraftforge.fml.common.ModMetadata
 *  net.minecraftforge.fml.common.SidedProxy
 *  net.minecraftforge.fml.common.event.FMLInitializationEvent
 *  net.minecraftforge.fml.common.event.FMLPostInitializationEvent
 *  net.minecraftforge.fml.common.event.FMLPreInitializationEvent
 *  net.minecraftforge.fml.common.event.FMLServerStartingEvent
 *  org.apache.logging.log4j.Level
 *  org.apache.logging.log4j.Logger
 *  org.apache.logging.log4j.core.Appender
 *  org.apache.logging.log4j.core.Layout
 *  org.apache.logging.log4j.core.Logger
 *  org.apache.logging.log4j.core.appender.FileAppender
 *  org.apache.logging.log4j.core.appender.FileAppender$Builder
 *  org.apache.logging.log4j.core.layout.PatternLayout
 */
package eos.moe.dragoncore;

import eos.moe.dragoncore.fi;
import eos.moe.dragoncore.fx;
import eos.moe.dragoncore.ir;
import eos.moe.dragoncore.sf;
import eos.moe.dragoncore.td;
import eos.moe.dragoncore.yh;
import eos.moe.dragoncore.zn;
import java.io.File;
import net.minecraft.command.ICommand;
import net.minecraft.command.ServerCommandManager;
import net.minecraft.nbt.NBTTagCompound;
import net.minecraft.server.MinecraftServer;
import net.minecraftforge.common.config.Configuration;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.ModMetadata;
import net.minecraftforge.fml.common.SidedProxy;
import net.minecraftforge.fml.common.event.FMLInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPostInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;
import net.minecraftforge.fml.common.event.FMLServerStartingEvent;
import org.apache.logging.log4j.Level;
import org.apache.logging.log4j.Logger;
import org.apache.logging.log4j.core.Appender;
import org.apache.logging.log4j.core.Layout;
import org.apache.logging.log4j.core.appender.FileAppender;
import org.apache.logging.log4j.core.layout.PatternLayout;

@Mod(modid="nbtedit", name="In-game NBTEdit", version="1.11.2-2.0.2", acceptableRemoteVersions="*", acceptedMinecraftVersions="[1.12.2]")
public class ov {
    public static final String g = "nbtedit";
    public static final String t = "In-game NBTEdit";
    public static final String r = "1.11.2-2.0.2";
    public static final zn x = new zn();
    public static final sf v = new sf();
    public static Logger m;
    public static fi c;
    public static boolean q;
    public static boolean b;
    @Mod.Instance(value="nbtedit")
    private static ov o;
    @SidedProxy(clientSide="eos.moe.dragoncore.ns", serverSide="eos.moe.dragoncore.fx")
    public static fx y;
    private td k;
    public static final String ALLATORIxDEMO;

    public ov() {
        ov a2;
    }

    @Mod.EventHandler
    public void ALLATORIxDEMO(FMLPreInitializationEvent a2) {
        Configuration a3 = new Configuration(a2.getSuggestedConfigurationFile());
        a3.load();
        q = a3.get("General", "opOnly", true, "true if only Ops can NBTEdit; false allows users in creative mode to NBTEdit").getBoolean(true);
        b = a3.get("General", "editOtherPlayers", false, "true if editing players other then your self is allowed. false by default. USE AT YOUR OWN RISK").getBoolean(false);
        if (a3.hasChanged()) {
            a3.save();
        }
        m = a2.getModLog();
        org.apache.logging.log4j.core.Logger a4 = (org.apache.logging.log4j.core.Logger)m;
        a4.setAdditive(false);
        a4.setLevel(Level.ALL);
        PatternLayout a5 = PatternLayout.newBuilder().withPattern("[%d{MM-dd HH:mm:ss}] [%level]: %msg%n").build();
        FileAppender.Builder a6 = FileAppender.newBuilder();
        a6.withFileName("logs/NBTEdit.log").withName("NBTEdit File Appender").withLayout((Layout)a5).withIgnoreExceptions(false);
        FileAppender a7 = a6.build();
        a7.start();
        a4.addAppender((Appender)a7);
        ModMetadata a8 = a2.getModMetadata();
        a8.autogenerated = false;
        a8.modId = g;
        a8.version = r;
        a8.name = t;
        a8.authorList.add("Davidee");
        a8.credits = "Thanks to Mojang, Forge, and all your support.";
        a8.description = "Allows you to edit NBT Tags in-game.\nPlease visit the URL above for help.";
        a8.url = "http://www.minecraftforum.net/topic/1558668-151/";
    }

    @Mod.EventHandler
    public void ALLATORIxDEMO(FMLInitializationEvent a2) {
        m.trace("NBTEdit Initalized");
        a.k = new td(new File(new File(y.ALLATORIxDEMO(), "saves"), "NBTEdit.dat"));
        v.c();
    }

    @Mod.EventHandler
    public void ALLATORIxDEMO(FMLPostInitializationEvent a2) {
        y.ALLATORIxDEMO();
    }

    @Mod.EventHandler
    public void ALLATORIxDEMO(FMLServerStartingEvent a2) {
        MinecraftServer a3 = a2.getServer();
        ServerCommandManager a4 = (ServerCommandManager)a3.func_71187_D();
        a4.func_71560_a((ICommand)new ir());
        m.trace("Server Starting -- Added \"/nbtedit\" command");
    }

    public static void ALLATORIxDEMO(Level a2, String a3) {
        m.log(a2, a3);
    }

    public static void ALLATORIxDEMO(String a2, String a3, Throwable a4) {
        m.warn("class: " + a2 + " method: " + a3, a4);
    }

    public static void ALLATORIxDEMO(NBTTagCompound a2) {
        yh a3 = new yh(a2);
        String a4 = "";
        for (String a5 : a3.ALLATORIxDEMO()) {
            a4 = a4 + ALLATORIxDEMO + "\t\t\t" + a5;
        }
        ov.ALLATORIxDEMO(Level.TRACE, a4);
    }

    public static td ALLATORIxDEMO() {
        return ov.o.k;
    }

    static {
        c = null;
        q = true;
        b = false;
        ALLATORIxDEMO = System.getProperty("line.separator");
    }
}

